
// name
::Const.Strings.PerkName.NggHCharmEnemySpider <- "Enthralled Beast - Arachnids";
::Const.Strings.PerkName.NggHCharmEnemyDirewolf <- "Enthralled Beast - Carnivorans";
::Const.Strings.PerkName.NggHCharmEnemyAlp <- "Enthralled Beast - Alps";
::Const.Strings.PerkName.NggHCharmEnemyGhoul <- "Enthralled Beast - Nachzehrers";
::Const.Strings.PerkName.NggHCharmEnemyUnhold <- "Enthralled Beast - Unholds";
::Const.Strings.PerkName.NggHCharmEnemySchrat <- "Enthralled Beast - Schrats";
::Const.Strings.PerkName.NggHCharmEnemyLindwurm <- "Enthralled Beast - Lindwurms";
::Const.Strings.PerkName.NggHCharmEnemyOrk <- "Captive Brute - Orks";
::Const.Strings.PerkName.NggHCharmEnemyGoblin <- "Captive Trickter - Goblins";

::Const.Strings.PerkName.NggHCharmBasic <- "Charm 101";
::Const.Strings.PerkName.NggHCharmWords <- "Lustful Words";
::Const.Strings.PerkName.NggHCharmAppearance <- "Seductive Appearance";
::Const.Strings.PerkName.NggHCharmSpec <- "Charm Mastery";
::Const.Strings.PerkName.NggHCharmNudist <- "Nudist";

::Const.Strings.PerkName.NggHHexHexer <- "Hexer";
::Const.Strings.PerkName.NggHHexMastery <- "Hex Mastery";
::Const.Strings.PerkName.NggHHexSharePain <- "Share The Pain";
::Const.Strings.PerkName.NggHHexSuffering <- "Hex of Suffering";
::Const.Strings.PerkName.NggHHexWeakening <- "Hex of Weakening";
::Const.Strings.PerkName.NggHHexVulnerability <- "Hex of Vulnerability";
::Const.Strings.PerkName.NggHHexMisfortune <- "Hex of Misfortune";

::Const.Strings.PerkName.NggH_BDSM_WhipLash <- "Whip Lash";
::Const.Strings.PerkName.NggH_BDSM_WhipMastery <- "Whip Mastery";
::Const.Strings.PerkName.NggH_BDSM_MaskOn <- "Mask On";
::Const.Strings.PerkName.NggH_BDSM_Bondage <- "Let\'s Play Bondage";
::Const.Strings.PerkName.NggH_BDSM_WhipPunish <- "Bad Boys Must Be Punished";
::Const.Strings.PerkName.NggH_BDSM_WhipLove <- "Love Is Pain";
::Const.Strings.PerkName.NggH_BDSM_DommyMommy <- "Dominant Demeanor";

::Const.Strings.PerkName.NggHLuftPattingSpec <- "Petting Mastery";
::Const.Strings.PerkName.NggHLuftUnholyFruits <- "Naughty Luft";
::Const.Strings.PerkName.NggHLuftInnocentLook <- "Innocent Face";
::Const.Strings.PerkName.NggHLuftGhoulBeauty <- "Ghoulish Beauty";

//For unique beast perks
::Const.Strings.PerkName.NggHEggBreedingMachine <- "Breeding Machine";
::Const.Strings.PerkName.NggHEggInherit <- "Inheritance";
::Const.Strings.PerkName.NggHEggNaturalSelection <- "Natural Selection";
::Const.Strings.PerkName.NggHEggAttachSpider <- "I Need an Uber";

::Const.Strings.PerkName.NggHSpiderBite <- "Puncturing Bite";
::Const.Strings.PerkName.NggHSpiderVenom <- "Poison Mastery";
::Const.Strings.PerkName.NggHSpiderWeb <- "Weave Web Mastery";

::Const.Strings.PerkName.NggHSerpentBite <- "Gorge";
::Const.Strings.PerkName.NggHSerpentDrag <- "Constricting Grip";
::Const.Strings.PerkName.NggHSerpentVenom <- "Venom Gland";
::Const.Strings.PerkName.NggHSerpentGiant <- "Oversized Snake";
// hyena
::Const.Strings.PerkName.NggHHyenaBite <- "Meat-Tearing Bite";
// wolf
::Const.Strings.PerkName.NggHWolfBite <- "Strong Canine Jaw";
::Const.Strings.PerkName.NggHWolfThickHide <- "Thick Fur";
::Const.Strings.PerkName.NggHWolfEnrage <- "Overwhelm Your Prey";
::Const.Strings.PerkName.NggHWolfRabies <- "Rabies";

::Const.Strings.PerkName.NggHAlpNightmareSpec <- "Dream Eater";
::Const.Strings.PerkName.NggHAlpSleepSpec <- "Overslept";
::Const.Strings.PerkName.NggHAlpAfterWake <- "Horrified Wake Up";
::Const.Strings.PerkName.NggHAlpAfterimage <- "Afterimage";
::Const.Strings.PerkName.NggHAlpLivingNightmare <- "Living Nightmare";
::Const.Strings.PerkName.NggHAlpMindBreak <- "Mind Break";

::Const.Strings.PerkName.NggHAlpControlFlame <- "Fire Bender";
::Const.Strings.PerkName.NggHAlpFieceFlame <- "Scorch";
::Const.Strings.PerkName.NggHAlpHellishFlame <- "Inferno";
::Const.Strings.PerkName.NggHAlpShadowCopy <- "Shadow Copy";

::Const.Strings.PerkName.NggHNacho <- "Ghoul";
::Const.Strings.PerkName.NggHNachoEat <- "Strengthening Meal";
::Const.Strings.PerkName.NggHNachoFrenzy <- "Frenzy";
::Const.Strings.PerkName.NggHNachoVomit <- "Throw Up";
::Const.Strings.PerkName.NggHNachoBigTummy <- "Big Tummy";
::Const.Strings.PerkName.NggHNachoScavenger <- "Scavenger";

::Const.Strings.PerkName.NggHUnholdUnarmedAttack <- "Hand-to-Hand Attack";
::Const.Strings.PerkName.NggHUnholdFling <- "Forceful Throw";

::Const.Strings.PerkName.NggHSchratShield <- "Grow Shield Mastery";
::Const.Strings.PerkName.NggHSchratSapling <- "Obedient Sapling";
::Const.Strings.PerkName.NggHSchratUproot <- "Strong Root";
::Const.Strings.PerkName.NggHSchratUprootAoE <- "Shatter The Earth";

::Const.Strings.PerkName.NggHLindwurmAcid <- "Spit Acidic Blood";
::Const.Strings.PerkName.NggHLindwurmIntimidate <- "Intimidate";
::Const.Strings.PerkName.NggHLindwurmBody <- "Powerful Constitution";

::Const.Strings.PerkName.NggHKrakenBite <- "Rupturing Bite";
::Const.Strings.PerkName.NggHKrakenDevour <- "Insatiable Hunger";
::Const.Strings.PerkName.NggHKrakenEnsnare <- "Bone Shattering Grip";
::Const.Strings.PerkName.NggHKrakenMove <- "Slippery Tentacle";
::Const.Strings.PerkName.NggHKrakenSwing <- "Sweep";
::Const.Strings.PerkName.NggHKrakenTentacle <- "Rubbering Skin";

::Const.Strings.PerkName.NggHGoblinMountTraining <- "Mount Training";
::Const.Strings.PerkName.NggHGoblinMountedArchery <- "Mounted Archery";
::Const.Strings.PerkName.NggHGoblinMountedCharge <- ::Const.Strings.PerkName.LegendHorseCharge;

::Const.Strings.PerkName.NggHGhostGhastlyTouch <- "Death Touch";
::Const.Strings.PerkName.NggHGhostSpectralBody <- "Shapeless Phantom";
::Const.Strings.PerkName.NggHGhostVanish <- "Vanish";
::Const.Strings.PerkName.NggHGhostPhase <- "Phase Through";
::Const.Strings.PerkName.NggHGhostSoulEater <- "Soul Eater";

::Const.Strings.PerkName.NggHMiscLineBreaker <- "Line Breaker";
::Const.Strings.PerkName.NggHMiscChampion <- "The Champion";
::Const.Strings.PerkName.NggHMiscDaytime <- "Endure The Light";
::Const.Strings.PerkName.NggHMiscNighttime <- "Nocturnal";
::Const.Strings.PerkName.NggHMiscFairGame <- "Fair Game";

//-------------
// description
::Const.Strings.PerkDescription.NggHCharmEnemySpider <- "\'The creepy crawlies in the depth of the forest, they would be suited to be your servants and soldiers.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Allows you to permanently charm Webknecht.\n• Satisfies one of two conditions to permanently charm Redback Spider.\n• Grants [color=" + ::Const.UI.Color.PositiveValue + "]Immunity[/color] to be rooted by nets, webs or grasping vines.";
::Const.Strings.PerkDescription.NggHCharmEnemyDirewolf <- "\'Who wouldn\'t want to own a 5 feet tall pet dog. Nothing could be better than seeing them mauling fools who dare to make an enemy of you.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Allows you to permanently charm Direwolf, Hyena, Bear.\n• Satisfies one of two conditions to permanently charm White Direwolf.\n• Initiative is increased by [color=" + ::Const.UI.Color.PositiveValue + "]8%[/color] and builds up [color=" + ::Const.UI.Color.PositiveValue + "]2[/color] less Fatigue for each tile travelled.";
::Const.Strings.PerkDescription.NggHCharmEnemyAlp <- "\'Dream eater or nightmare caller, such creatures should be servants for a beauty likes you.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Alp.\n• Satisfies one of two conditions to permanently charm Demon Alp.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+15[/color] Resolve at morale checks against fear, panic or mind control effects.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Sleep[/color] skill gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to put a target to sleep.";
::Const.Strings.PerkDescription.NggHCharmEnemyGhoul <- "\'Hungry monkeys or big fricking starving gorillas are probably nice exotic pets.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Nachzehrer.\n• Satisfies one of two conditions to permanently charm Skin Ghoul.\n• Hitpoints are increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].\n• Initiative is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].";
::Const.Strings.PerkDescription.NggHCharmEnemyUnhold <- "\'Giants that can even dwarf the tallest orc. You would want mighty creatures as them to be your bodyguards.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Unhold, Frost Unhold, Swamp Unhold, Armored Unhold.\n• Satisfies one of two conditions to permanently charm Rock Unhold.\n• Max Fatigue is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].\n• Hitpoints are increased by [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color].";
::Const.Strings.PerkDescription.NggHCharmEnemySchrat <- "\'Sentient ancient trees that are seen as guardian of the forest. Having them as your guardians should be more appropriate!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Schrat.\n• Satisfies one of two conditions to permanently charm Heartwood Schrat.\n• Melee Defense and Ranged Defense are increased by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.\n• Damage taken is reduced by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color]. Does not affect damage from mental attacks or status effects.";
::Const.Strings.PerkDescription.NggHCharmEnemyLindwurm <- "Some say they are giant serpents, some call them as dragons. All to describe certain fearsome beasts that have acidic blood and a towering body. Imagine of having one under your command. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Lindwurm.\n• Satisfies one of two conditions to permanently charm Stollwurm.\n• Reduces the Resolve of any opponent engaged in melee by the amount equals to [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color] of your current Resolve.";
::Const.Strings.PerkDescription.NggHCharmEnemyOrk <- "\'Warriors with physical strength that no human can match. Such brute strength should be used to fight for your causes.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Orc Berserker, Orc Warrior, Orc Elite.\n• Satisfies one of two conditions to permanently charm Orc Warlord and Orc Behemoth.\n• Your Initiative is reduced only by [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] of your accumulated Fatigue, instead of all of it.";
::Const.Strings.PerkDescription.NggHCharmEnemyGoblin <- "\'Goblins might be small and weak but they have tons of trick up their sleeves. Such cunning creatures are good for certain dirty jobs.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to permanently charm Goblin Overseer and Goblin Shaman.\n• Grants [color=" + ::Const.UI.Color.PositiveValue + "]Immunity[/color] to being overwhelmed.\n• Ranged Defense is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10[/color] points.";

::Const.Strings.PerkDescription.NggHCharmBasic <- "\'Learn the basic of how to steal other\'s heart. First lesson, with a good pair of ripe and juicy pears, men will fall for your charm.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Charm[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Captive Charm[/color] skills gain an additional [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] chance to charm.\n• Grants [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] barter skill, increasing sell prices, reducing buy prices and increasing pay for delivery contracts.";
::Const.Strings.PerkDescription.NggHCharmWords <- "\'Enchanted words that can wake up any sleeping snake down below.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.PositiveValue + "]Expands[/color] your charm capability to affect stronger humans, such as Knight, Sergent, Officer, Nomad Leader, Bandit Leader, Barbarian Chosen, etc.\n• Resolve is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].\n• Max Fatigue is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].";
::Const.Strings.PerkDescription.NggHCharmAppearance <- "\'A gorgeous appearance that no men can resist. How can such beauty exist?\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to charm Swordmaster, Blade Dancer, Master Archer, Desert Stalker, Hedge Knight, Nomad Executioner, Barbarian King and Bandit Warlord.\n• Increases the duration of [color=" + ::Const.UI.Color.NegativeValue + "]Charmed[/color] effect by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] turn. The bonus duration can not be reduced by [color=" + ::Const.UI.Color.NegativeValue + "]Resilient[/color] perk.";
::Const.Strings.PerkDescription.NggHCharmSpec <- "\'Master the art of capturing other\'s heart. Don\'t you want a dommy mommy? C\'mere! Let mommy comfort you!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Charm[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Captive Charm[/color] skills gain an additional [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color] to charm.\n• Allows you to permanently charm Champion enemies.\n• Satisfies the last condition to permanently charm Orc Warlord, Orc Behemoth and Legendary beasts.";
::Const.Strings.PerkDescription.NggHCharmNudist <- "\'Real slut doesn\'t need cloth.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n Gains the below effects while not wearing both armour and a helmet:\n• Gains another stack of nimble.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Charm[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Captive Charm[/color] skills gain an additional [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] to charm.";

::Const.Strings.PerkDescription.NggHHexHexer <- "\'You have no idea how much power a hexer has over their curses.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n When attacking a target affected by [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] effect, apply the effects below: \n• Attack Damage is increased by [color=" + ::Const.UI.Color.PositiveValue + "]33%[/color].\n• Hit chance is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].";
::Const.Strings.PerkDescription.NggHHexMastery <- "\'Master the art of hexing, your ability to curse someone has never been this good before.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Reduces the AP cost by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color], if you have [color=" + ::Const.UI.Color.NegativeValue + "]Protected by a Hex[/color] effect.\n• Experience Gain is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].";
::Const.Strings.PerkDescription.NggHHexSharePain <- "\'No one should be in pain alone!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Inflicts an additional [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] effect to another random enemy within your vision.\n• Once per round, damage from all sources (except from [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] effect) inflicted on one of your hexed target will also be inflicted on the other hexed targets, yourself is excluded.";
::Const.Strings.PerkDescription.NggHHexSuffering <- "\'A curse that brings a greater suffer! Let them take on your burden.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] active skill is upgraded into [color=" + ::Const.UI.Color.NegativeValue + "]Hex of Suffering[/color].\n• Hitpoints are increased by [color=" + ::Const.UI.Color.PositiveValue + "]18%[/color]. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Hex of Suffering effects:[/u][/color] \n• Transfers certain types of negative status effect ([color=" + ::Const.UI.Color.NegativeValue + "]Bleeding[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Poisoned[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Dazed[/color], etc) to a hexed victim \n\n[color=" + ::Const.UI.Color.NegativeValue + "]You can learn one perk in this perk group and only one, no more[/color]";
::Const.Strings.PerkDescription.NggHHexWeakening <- "\'A curse that can cause one to be weak and old.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] active skill is upgraded into [color=" + ::Const.UI.Color.NegativeValue + "]Hex of Weakening[/color].\n• Fatigue Recovery per turn is increased by [color=" + ::Const.UI.Color.PositiveValue + "]14%[/color]. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Hex of Weakening effects:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]-40%[/color] Attack Damage\n• [color=" + ::Const.UI.Color.NegativeValue + "]-33%[/color] Max Fatigue\n• [color=" + ::Const.UI.Color.NegativeValue + "]-5[/color] Fatigue Recovery per turn \n\n[color=" + ::Const.UI.Color.NegativeValue + "]You can learn one perk in this perk group and only one, no more[/color]";
::Const.Strings.PerkDescription.NggHHexVulnerability <- "\'A curse that causes new wounds to become more severe than usual.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] active skill is upgraded into [color=" + ::Const.UI.Color.NegativeValue + "]Hex of Vulnerability[/color].\n• Damage Taken to Hitpoints is reduced by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.\n• Damage Taken to Armor is reduced by [color=" + ::Const.UI.Color.PositiveValue + "]15[/color] points. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Hex of Vulnerability effects:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]+15%[/color] Damage Taken\n• [color=" + ::Const.UI.Color.NegativeValue + "]-25%[/color] Initiative \n\n[color=" + ::Const.UI.Color.NegativeValue + "]You can learn one perk in this perk group and only one, no more[/color]";
::Const.Strings.PerkDescription.NggHHexMisfortune <- "\'A curse that brings bad luck.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Hex[/color] active skill is upgraded into [color=" + ::Const.UI.Color.NegativeValue + "]Hex of Misfortune[/color].\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to have any attacker require two successful attack rolls in order to hit.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to have any negative morale check require two successful rolls in order to affect you. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Hex of Misfortune effects:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]-12%[/color] of total Hit Chance\n• [color=" + ::Const.UI.Color.NegativeValue + "]-10%[/color] of total Dodge Chance \n\n[color=" + ::Const.UI.Color.NegativeValue + "]You can learn one perk in this perk group and only one, no more[/color]";

::Const.Strings.PerkDescription.NggH_BDSM_WhipLash <- "\'It\'s so fast, you can hear the cracking sound from a far. How can anyone dodge this?\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n Gains the below effects while equipped with a whip:\n• Gains Melee Skill equal to [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color] of your current Initiative.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Whip[/color] active skill gains [color=" + ::Const.UI.Color.PositiveValue + "]+12%[/color] Attack Damage and [color=" + ::Const.UI.Color.PositiveValue + "]+6%[/color] Armor Penetration for each tile between you and the target.";
::Const.Strings.PerkDescription.NggH_BDSM_WhipMastery <- "\'Master whips to hit where it hurts the most.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• This perk is also treated as [color=" + ::Const.UI.Color.NegativeValue + "]Cleaver Mastery[/color].\n• [color=" + ::Const.UI.Color.NegativeValue + "]Whip[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Flaggelate[/color] active skills gain [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] Attack Damage for each stack of [color=" + ::Const.UI.Color.NegativeValue + "]Bleeding[/color] effect on the target.\n• Whip weapon skills have their AP cost reduced by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color].";
::Const.Strings.PerkDescription.NggH_BDSM_MaskOn <- "\'Dear! Is it it kinky to put on a mask?\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] Resolve for each point of pentalty to vision your helmet has.\n• Reduces the fatigue cost of your whip weapon skills equal to the pentalty to vision your helmet has.";
::Const.Strings.PerkDescription.NggH_BDSM_Bondage <- "\'Trust me, dear! We\'ll have a fun time.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\nApplies the below effects when using a valid skill to target an enemy trapped in net, vines or web: \n• [color=" + ::Const.UI.Color.NegativeValue + "]Charm[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Captive Charm[/color] skills gain [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to charm.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Whip[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Flaggelate[/color] active skills gain [color=" + ::Const.UI.Color.PositiveValue + "]+25%[/color] Attack Damage and [color=" + ::Const.UI.Color.PositiveValue + "]+15%[/color] Armor Penetration.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Disarm[/color] active skill gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit.";
::Const.Strings.PerkDescription.NggH_BDSM_WhipPunish <- "\'Do as mommy said or you will be whipped.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Gains [color=" + ::Const.UI.Color.NegativeValue + "]Crack the Whip[/color] active skill while equipped with a whip.\n• Costs 4 AP and builds 13 Fatigue.\n• Has a range of [color=" + ::Const.UI.Color.PositiveValue + "]3[/color] tiles.\n• Inflicts [color=" + ::Const.UI.Color.DamageValue + "]2[/color] - [color=" + ::Const.UI.Color.DamageValue + "]5[/color] damage that ignores armor to the target.\n• Gives the targeted simp the [color=" + ::Const.UI.Color.NegativeValue + "]Whipped[/color] status effect, increasing many of their stats for 2 rounds.\n• Resets the morale of the targeted simp to \'Steady\' if currently below.";
::Const.Strings.PerkDescription.NggH_BDSM_WhipLove <- "\'It\'s not abuse if they love it.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Every time your [color=" + ::Const.UI.Color.NegativeValue + "]Whip[/color] or [color=" + ::Const.UI.Color.NegativeValue + "]Flaggelate[/color] active skill successfully lands a hit, put a \"whipped\" counter on that target.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Charm[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Captive Charm[/color] skills gain [color=" + ::Const.UI.Color.PositiveValue + "]+4%[/color] chance to charm for each \"whipped\" counter on that target [b](max: 20%)[/b].\n• [color=" + ::Const.UI.Color.NegativeValue + "]Whip[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Flaggelate[/color] active skills gain additional Attack Damage equal to [color=" + ::Const.UI.Color.PositiveValue + "]12%[/color] of current Resolve [b](max: 30)[/b].";
::Const.Strings.PerkDescription.NggH_BDSM_DommyMommy <- "\'Have I told you to stop? Don\'t stop till i say so. Now clean my feet properly.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Gains [color=" + ::Const.UI.Color.NegativeValue + "]Fearsome[/color] perk for free.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Crack the Whip[/color] skill also improves your morale.\n• The bonuses of [color=" + ::Const.UI.Color.NegativeValue + "]Whipped[/color] effect from [color=" + ::Const.UI.Color.NegativeValue + "]Crack A Whip[/color] skill are increased by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.";

::Const.Strings.PerkDescription.NggHLuftPattingSpec <- "\'Master the art of petting head. No head can be left without being petted.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Petting[/color] skill builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Petting[/color] skill deals [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] more damage.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Petting[/color] skill has a [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] chance to distract the target.";
::Const.Strings.PerkDescription.NggHLuftUnholyFruits <- "\'Luft has learnt how to use his two unholy fruits for certain purposes.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Charm[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Captive Charm[/color] skills gain an additional [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] to charm.\n• Grants [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] barter skill, increasing sell prices, reducing buy prices and increasing pay for delivery contracts.";
::Const.Strings.PerkDescription.NggHLuftInnocentLook <- "\'Using his innocent and smol nacho appearance to make more humans think he\'s cute so he can pet them when they have lower their guard.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n•[color=" + ::Const.UI.Color.PositiveValue + "]Expands[/color] your charm capability to affect stronger humans, such as Knight, Sergent, Officer, Nomad Leader, Bandit Leader, Barbarian Chosen, etc.\n• Resolve is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].\n• Max Fatigue is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].";
::Const.Strings.PerkDescription.NggHLuftGhoulBeauty <- "\'A Charming ghoulish body that can make any perverted human falls in love with Luft. They like me! They love me! They let me pet them!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Allows you to charm Swordmaster, Blade Dancer, Master Archer, Desert Stalker, Hedge Knight, Nomad Executioner, Barbarian King and Bandit Warlord.\n• Increases the duration of [color=" + ::Const.UI.Color.NegativeValue + "]Charmed[/color] effect by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] turn. The bonus duration can not be reduced by [color=" + ::Const.UI.Color.NegativeValue + "]Resilient[/color] perk.";
//For unique beast perks
::Const.Strings.PerkDescription.NggHEggBreedingMachine <- "\'Master what you are good at. Producing eggs, not to eat thou!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Hatch Egg[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Hatch All Eggs[/color] skills build up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• At the start of each turn, Has a [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color] chabce to gain a free egg.";
::Const.Strings.PerkDescription.NggHEggInherit <- "\'Like father like son.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Hatched spiderlings inherits most of your perks.";
::Const.Strings.PerkDescription.NggHEggNaturalSelection <- "\'Let nature do their work.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Hatched spiderlings have higher raw stats than those hatched before them.";
::Const.Strings.PerkDescription.NggHEggAttachSpider <- "\'It is sad when you do not have legs. Wishing for a pairs of leg would be asking too much. Well!!! At least you can ask your spider friends or from your own offsprings for an Uber ride.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Gains the ability to mount on Spiders or certain creatures such as Wardogs, Warhounds, Wolves.";

::Const.Strings.PerkDescription.NggHSpiderBite <- "\'Strong spider bite that is capable of puncturing the toughest and sturdiest armor.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Webknecht Bite[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Redback Webknecht Bite[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Gains [color=" + ::Const.UI.Color.DamageValue + "]1[/color]-[color=" + ::Const.UI.Color.DamageValue + "]5[/color] Attack Damage.\n• Gains an additional [color=" + ::Const.UI.Color.PositiveValue + "]+15%[/color] of any damage ignores armor.\n• Has [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] chance to become a puncturing attack that is completely ignore armor.";
::Const.Strings.PerkDescription.NggHSpiderVenom <- "\'An even more deadly venom, your poor victim would surely die faster.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Poisoned[/color] effect inflicted by your bite doubles the starting damage and allows it to stack its poison damage.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Redback Poisoned[/color] effect inflicted by your bite deals double the damage and makes it more potent as the target get bitten more.";
::Const.Strings.PerkDescription.NggHSpiderWeb <- "\'Master the ability to weave and create web so you can make the strongest web with little effort.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Weave Web[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• The less accumulated Fatigue you have the harder for the enemy to break free from your web.\n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Removes the cooldown.";

::Const.Strings.PerkDescription.NggHSerpentBite <- "\'Lightning attack that can deliver a more powerful bite.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Serpent Bite[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Only costs [color=" + ::Const.UI.Color.PositiveValue + "]4[/color] AP.\n• Attack Damage is increased by [color=" + ::Const.UI.Color.DamageValue + "]8[/color]-[color=" + ::Const.UI.Color.DamageValue + "]15[/color] points.\n• Effectiveness vs. Armor is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].";
::Const.Strings.PerkDescription.NggHSerpentDrag <- "\'With strong muscles, any prey can easily be disable in this unbreakable constriction.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Serpent Drag[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Increases maximum range by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] tile.\n• Now also deals up to [color=" + ::Const.UI.Color.DamageValue + "]10[/color] armor piercing damage.";
::Const.Strings.PerkDescription.NggHSerpentVenom <- "\'Evolve to gain a venom gland to poison your prey. Deadly but doesn\'t persist long.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Serpent Bite[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Inflicts an additional [color=" + ::Const.UI.Color.DamageValue + "]20[/color] poison damage per turn.\n• The [color=" + ::Const.UI.Color.NegativeValue + "]Poisoned[/color] effect inflicted by this perk only lasts for 1 turn.";
::Const.Strings.PerkDescription.NggHSerpentGiant <- "\'What could be more terrifying than a big snake? A gigantic snake!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Serpent Drag[/color] skill has a chance to [color=" + ::Const.UI.Color.PositiveValue + "]Disarm[/color] its dragged target based on current Melee skill.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Serpent Drag[/color] skill allows you to drag allies with immunity to Knock back and Grab.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Serpent Bite[/color] skill has its attack range increased by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color].";

// hyena
::Const.Strings.PerkDescription.NggHHyenaBite <- "\'Razor sharp fangs that are capable of creating gruesome bleeding wounds.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Hyena Bite[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Attack Damage is increased by [color=" + ::Const.UI.Color.DamageValue + "]10[/color] points.\n• Effectiveness vs. Armor is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].\n• Bleeding damage inflicted by bites is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.";
// wolf
::Const.Strings.PerkDescription.NggHWolfBite <- "\'Powerful jaw muscles and tough fangs to help crush armor and tear flesh apart.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Direwolf Bite[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Attack Damage is increased by [color=" + ::Const.UI.Color.DamageValue + "]10[/color] points.\n• Effectiveness vs. Armor is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].";
::Const.Strings.PerkDescription.NggHWolfThickHide <- "\'Thick and tough fur that can stop attacks from causing severe injury.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Takes [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color] less damage to armor.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]60[/color] points of natural armor to both head and body armors.";
::Const.Strings.PerkDescription.NggHWolfEnrage <- "\'Fast and furious attacks that leave your overwhelmed victim no way to escape or fight back.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  Gains effect below for each stack of [color=" + ::Const.UI.Color.NegativeValue + "]Overwhelmed[/color] effect on your target: \n• Hit chance is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].\n• Attack Damage is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color].\n• Gains an additional [color=" + ::Const.UI.Color.PositiveValue + "]+2%[/color] of any damage ignores armor.";
::Const.Strings.PerkDescription.NggHWolfRabies <- "\'Your puppy has rabies. That is not good, right? Do not pet it!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Attack Damage is increased by [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color].\n• Melee Skill is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.\n• Hitpoints are increased by [color=" + ::Const.UI.Color.PositiveValue + "]20[/color] points.\n• Resolve is increased by [color=" + ::Const.UI.Color.PositiveValue + "]20[/color] points.";

::Const.Strings.PerkDescription.NggHAlpNightmareSpec <- "\'Feed on the nightmare and terror of your victim to restore your own vitality.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Nightmare[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Gains additional damage equal to [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color] of current Resolve.\n• Restores your Hitpoints up to [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] of the damage dealt.";
::Const.Strings.PerkDescription.NggHAlpSleepSpec <- "\'Master your ability to put your prey in a long lasting sleep.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Sleep[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Increases the chance to put a target to sleep by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color] of current Resolve.\n• Increases the duration of [color=" + ::Const.UI.Color.NegativeValue + "]Sleeping[/color] effect by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] turn.\n• Reduces the AP cost by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color].";
::Const.Strings.PerkDescription.NggHAlpAfterWake <- "\'Preys wake up by nightmare are easy to break.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Nightmare[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Ignores up to [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color] of target Resolve.\n• Has a [color=" + ::Const.UI.Color.PositiveValue + "]33%[/color] chance to not wake up the target. \n• When [color=" + ::Const.UI.Color.NegativeValue + "]Sleeping[/color] effect wears off by attacks, causes a morale check.";
::Const.Strings.PerkDescription.NggHAlpAfterimage <- "\'Become more annoying than ever.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  After teleporting by any mean, applies the below effect: \n• Grants [color=" + ::Const.UI.Color.NegativeValue + "]Afterimage[/color] effect that gives [color=" + ::Const.UI.Color.PositiveValue + "]+15[/color] Melee Defense and Ranged Defense and lasts till the start of your next turn.\n• Additional stack of [color=" + ::Const.UI.Color.NegativeValue + "]Afterimage[/color] effect only gives [color=" + ::Const.UI.Color.PositiveValue + "]+5[/color] Melee Defense and Ranged Defense."; 
::Const.Strings.PerkDescription.NggHAlpLivingNightmare <- "\'What would be more terrifying than a nightmare? A nightmare outside of a dream.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Nightmare[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Has a chance to spawn a living Nightmare upon killing an enemy.\n• The chance is depending on how many times you have used [color=" + ::Const.UI.Color.NegativeValue + "]Nightmare[/color] skill on the same target.";
::Const.Strings.PerkDescription.NggHAlpMindBreak <- "\'Definitely not some dirty shit from hentai.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 4 AP and builds 8 Fatigue.\n• Deals [color=" + ::Const.UI.Color.DamageValue + "]5[/color] - [color=" + ::Const.UI.Color.DamageValue + "]10[/color] armor ignoring damage.\n• Inflicts [color=" + ::Const.UI.Color.NegativeValue + "]Mind Broken[/color] effect which lowers affected target\'s Resolve by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Mind Broken[/color] effect lasts up to 3 turns and can also be stacked.";

::Const.Strings.PerkDescription.NggHAlpControlFlame <- "\'Better control over your fire, better safety for you. Be careful when having more than 2 demon alps, their fire can override each other.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Realm of Burning Nightmares[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• The flame will not hurt the caster.";
::Const.Strings.PerkDescription.NggHAlpFieceFlame <- "\'Raging flames that can burn down anything. Hell is here!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Realm of Burning Nightmares[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Increases the fire damage by [color=" + ::Const.UI.Color.DamageValue + "]5[/color]-[color=" + ::Const.UI.Color.DamageValue + "]20[/color] points.\n• Fire damage may cause horrible burnt wounds.\n• Duration of flame is [color=" + ::Const.UI.Color.NegativeValue + "]halved[/color].";
::Const.Strings.PerkDescription.NggHAlpHellishFlame <- "\'You might like Hell's Kitchen but i doubt you would like Hell Fire.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Realm of Burning Nightmares[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Applies fire damage as soon as the skill is used.\n• Increases the fire damage by [color=" + ::Const.UI.Color.DamageValue + "]5[/color]-[color=" + ::Const.UI.Color.DamageValue + "]12[/color] points.";
::Const.Strings.PerkDescription.NggHAlpShadowCopy <- "\'Two are better than one.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 7 AP and builds 30 Fatigue.\n• Allows you to engulf a huge area ([color=" + ::Const.UI.Color.PositiveValue + "]7[/color] tiles) with darkness that lasts for [color=" + ::Const.UI.Color.PositiveValue + "]3[/color] rounds.\n• Spawns a Nightmare monster if you have not controlled one already.\n• The darkness zone will keep respawning your Nightmare monster at the start of your turn after it was killed.";

::Const.Strings.PerkDescription.NggHNacho <- "Master your ghoulish abilities.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Max Fatigue is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].\n• [color=" + ::Const.UI.Color.NegativeValue + "]Frenzy[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Ghoul Claws[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Skin Ghoul Claws[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Gruesome Feast[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Swallow Whole[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Throw Up[/color] skills build up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.";
::Const.Strings.PerkDescription.NggHNachoEat <- "\'Eat and be strong! Ooga booga!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  Applies the effects below for each time [color=" + ::Const.UI.Color.NegativeValue + "]Gruesome Feast[/color] skill is used: \n• Attack Damage is increased by [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color].\n• Fatigue Recovery per turn is increased by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] points.\n• Resolve is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10[/color] points.\n• The effect lasts for [color=" + ::Const.UI.Color.PositiveValue + "]2[/color] turns.";
::Const.Strings.PerkDescription.NggHNachoFrenzy <- "\'Thrist for blood.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 3 AP and builds 25 Fatigue.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+15%[/color] Attack Damage.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+15%[/color] Melee Skill.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+50%[/color] Initiative.\n• Reduces [color=" + ::Const.UI.Color.NegativeValue + "]-50%[/color] Melee Defense.\n• Gains immunity to [color=" + ::Const.UI.Color.PositiveValue + "]Stun[/color].\n• Gains immunity to [color=" + ::Const.UI.Color.PositiveValue + "]Knock Back[/color] or [color=" + ::Const.UI.Color.PositiveValue + "]Grab[/color].\n• All active skills cost [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] less AP.\n• Applies additional [color=" + ::Const.UI.Color.NegativeValue + "]Overwhelmed[/color] effect (even if you have not learnt [color=" + ::Const.UI.Color.NegativeValue + "]Overwhelm[/color] perk).\n• The effect lasts for [color=" + ::Const.UI.Color.PositiveValue + "]2[/color] turns.";
::Const.Strings.PerkDescription.NggHNachoVomit <- "\'Uwwwww owhwhwhwh!\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 6 AP and builds 15 Fatigue.\n• Allows your 'last meal' to make its way out of your stomache.\n• Can not use [color=" + ::Const.UI.Color.NegativeValue + "]Swallow Whole[/color] skill until your next turn after you have used this skill.";
::Const.Strings.PerkDescription.NggHNachoBigTummy <- "\'A bigger belly means a bigger defensive bonus.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  Gains the effects below as long as you have [color=" + ::Const.UI.Color.NegativeValue + "]Devour[/color] effect: \n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+25%[/color] Resolve.\n• Reduces damage taken by [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color]. Does not affect damage from mental attacks or status effects.";
::Const.Strings.PerkDescription.NggHNachoScavenger <- "\'A feast after work! Don\'t mind if i do.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Feasts on leftovers corpses after participating in a battle, and if you do, gains [color=" + ::Const.UI.Color.NegativeValue + "]Well Fed[/color] effect. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Well Fed effect:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]+25%[/color] to one of these attribute (Max Action Point, Max Fatigue, Resolve, Initiative, Melee Skill, Melee Defense, Melee Damage, Experience Gain)\n• [color=" + ::Const.UI.Color.PositiveValue + "]-25%[/color] Daily Food Consumption \n• Lasts for a battle";

::Const.Strings.PerkDescription.NggHUnholdUnarmedAttack <- "\'Learn the basic about Hand-to-Hand combat.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 6 AP and builds 18 Fatigue.\n• A simple single target attack skill.\n• Has a [color=" + ::Const.UI.Color.NegativeValue + "]50%[/color] chance to knock back on hit.";
::Const.Strings.PerkDescription.NggHUnholdFling <- "\'When the throw can go to the moon.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Fling Back[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Costs only [color=" + ::Const.UI.Color.PositiveValue + "]3[/color] AP to use.\n• Applies [color=" + ::Const.UI.Color.NegativeValue + "]Dazed[/color] effect on hit.";

::Const.Strings.PerkDescription.NggHSchratShield <- "\'Experience and instinct have given you a better understanding on how to grow and use shield more efficient.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Grow Shield[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Grow Greenwood Shield[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Grants [color=" + ::Const.UI.Color.NegativeValue + "]Shieldwall[/color] effect on use.";
::Const.Strings.PerkDescription.NggHSchratSapling <- "\'Life-filled broken body part can easily be reborned into an intelligent Sapling.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Increases the chance to spawn Sapling after taking a hit by [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color].\n• Saplings can be controlled directly by player.";
::Const.Strings.PerkDescription.NggHSchratUproot <- "\'Stronger root to make more servere wound.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Uproot[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Shatter The Earth[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Attack Damage is increased by [color=" + ::Const.UI.Color.DamageValue + "]5[/color]-[color=" + ::Const.UI.Color.DamageValue + "]15[/color] points.\n• Effectiveness vs. Armor is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].";
::Const.Strings.PerkDescription.NggHSchratUprootAoE <- "\'A ground erupting attack, sending rock shrapnels everywhere.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 6 AP and builds 25 Fatigue.\n• Can hit up to 6 targets.\n• Has a [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit.\n• Removes all [color=" + ::Const.UI.Color.NegativeValue + "]Spearwall[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Shieldwall[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Riposte[/color] effects of all adjacent entities.";

::Const.Strings.PerkDescription.NggHLindwurmAcid <- "\'Hmm yes! An acid spitting dragon.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 5 AP, 60 HP and builds 30 Fatigue.\n• Has a range of [color=" + ::Const.UI.Color.PositiveValue + "]3[/color] tiles.\n• Covers the target and may be anyone nearby in acidic blood, creating grievous burnt wounds, melting away any kind of armor.\n• May inflict [color=" + ::Const.UI.Color.NegativeValue + "]Blinded[/color] effect if the attack lands on the head.";
::Const.Strings.PerkDescription.NggHLindwurmIntimidate <- "\'Scare them with your huge c... I mean snake.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 7 AP and builds 36 Fatigue.\n• On use, causes a morale check on any enemy within 3 tiles radius.\n• Reduces up to [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color] of Melee Skill, Ranged Skill, Melee Defense, Ranged Defense and Resolve of any enemy within 3 tiles radius.\n• This effect only lasts for [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] turn.";
::Const.Strings.PerkDescription.NggHLindwurmBody <- "\'Stronger is better.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Gorge[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Tail Thresh[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Tail Sweep[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Tail Split[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue.\n• Attack Damage is increased by [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color].";

::Const.Strings.PerkDescription.NggHKrakenBite <- "\'Your bite becomes more dangerous with sharpen teeth that can easily cause grievous bleelding.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Bite[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Attack Damage is increased by [color=" + ::Const.UI.Color.PositiveValue + "]8[/color]-[color=" + ::Const.UI.Color.PositiveValue + "]18[/color] points.\n• Inflicts an additional [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] bleeding damage.";
::Const.Strings.PerkDescription.NggHKrakenDevour <- "\'Hungrier than ever.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Devour[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Removes the cooldown completely.\n• On use, restores [color=" + ::Const.UI.Color.PositiveValue + "]25[/color]-[color=" + ::Const.UI.Color.PositiveValue + "]40[/color] of Hitpoints to all tentacles.";
::Const.Strings.PerkDescription.NggHKrakenEnsnare <- "\'When you think about being dragged to a big flicking mouth is bad enough, now imagine being squeezed to pulp before getting eaten.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Squeeze Prey[/color] deals [color=" + ::Const.UI.Color.PositiveValue + "]35%[/color] more damage, this is also applied to the damage over time while being ensnared by tentacle.";
::Const.Strings.PerkDescription.NggHKrakenMove <- "With the help of natural slime, your tenticles can move better than ever. Definitely not inspired by anything weird.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Tentacles build up [color=" + ::Const.UI.Color.PositiveValue + "]2[/color] less Fatigue for each tile travelled.\n• [color=" + ::Const.UI.Color.NegativeValue + "]Move Tentacle[/color] skill has its maximum range increased by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] tile.";
::Const.Strings.PerkDescription.NggHKrakenSwing <- "\'What better use of your tentacles than swinging it around? ...! Stop! we do not talk about that.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 5 AP and builds 36 Fatigue.\n• Can hit up to 3 targets at once.\n• Only for your tentacles.";
::Const.Strings.PerkDescription.NggHKrakenTentacle <- "\'Your skin is like rubber or perhaps latex too?! Capable of deflecting attacks and harder to be cut.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Reduces all damage taken by [color=" + ::Const.UI.Color.PositiveValue + "]15[/color] points.\n• Gains immunity to bleeding.";

::Const.Strings.PerkDescription.NggHGoblinMountTraining <- "\'Learn how to ride a mount.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Gains the ability to mount on Wardogs, Warhounds and Wolves.";
::Const.Strings.PerkDescription.NggHGoblinMountedArchery <- "\'Learn the proper ways to use ranged weapon while riding mount.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  Gains the effects below while you are riding a mount: \n• Removes the Ranged Damage penalty.\n• Reduces the Ranged Skill penalty from [color=" + ::Const.UI.Color.NegativeValue + "]-35%[/color] down to [color=" + ::Const.UI.Color.PositiveValue + "]-15%[/color]. \n• Throwing weapons gains additional damage if you have [color=" + ::Const.UI.Color.NegativeValue + "]Mounted Charge[/color] effect.";
::Const.Strings.PerkDescription.LegendHorseLiberty = "\'Through extensive roundpenning training, the mount gains trust in the movements of the rider.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  Gains the effects below while you are riding a mount: \n• Increases Resolve by [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color].\n• Builds up [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] less Fatigue for each tile travelled"; 
::Const.Strings.PerkDescription.NggHGoblinMountedCharge <- "\'Use the great weight and speed of the mount to charge forward.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 0 AP and builds 15 Fatigue.\n• Your first mounted charge attack may [color=" + ::Const.UI.Color.PositiveValue + "]Knock Back[/color], [color=" + ::Const.UI.Color.PositiveValue + "]Stagger[/color] or [color=" + ::Const.UI.Color.PositiveValue + "]Daze[/color] the target on hit.\n• Improves the bonus from [color=" + ::Const.UI.Color.NegativeValue + "]Mounted Charge[/color] effect up to [color=" + ::Const.UI.Color.PositiveValue + "]150%[/color] of the original bonus.";
// ghost
::Const.Strings.PerkDescription.NggHGhostGhastlyTouch <- "\'My touch is both fast and deadly!!!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Affected Skills:[/u][/color] [color=" + ::Const.UI.Color.NegativeValue + "]Ghastly Touch[/color] \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Costs [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] less AP.\n• Gains an additional [color=" + ::Const.UI.Color.DamageValue + "]0[/color] - [color=" + ::Const.UI.Color.DamageValue + "]5[/color] Attack Damage.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] hit chance.";
::Const.Strings.PerkDescription.NggHGhostSpectralBody <- "\'Like a shapeless moving shadow, You can hardly hit it.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Makes any incoming melee attacks has [color=" + ::Const.UI.Color.PositiveValue + "]-10%[/color] chance to hit you.\n• Grants a complete immunity to all ranged attacks.";
::Const.Strings.PerkDescription.NggHGhostVanish <- "\'I was there seconds ago, now i am here.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Upon taking damage, you will be automatically teleported to another place that is in most cases be at least 2-3 tiles away from enemies.";
::Const.Strings.PerkDescription.NggHGhostPhase <- "\'What do you think when you meet a ghost then seeing it passes through your body?\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 6 AP and builds 0 Fatigue.\n• Allows you to attack to up to 2 targets while also moving through those targets.\n• Deals armor ignoring damage.";
::Const.Strings.PerkDescription.NggHGhostSoulEater <- "\'A ghost feasts on the soul of living being? Now that sounds scary.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• [color=" + ::Const.UI.Color.NegativeValue + "]Ghastly Touch[/color], [color=" + ::Const.UI.Color.NegativeValue + "]Phase Through[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]Banshee Scream[/color] skills have [color=" + ::Const.UI.Color.PositiveValue + "]33%[/color] chance to recover a life for [color=" + ::Const.UI.Color.NegativeValue + "]Nine Lives[/color] perks after killing an enemy.";

::Const.Strings.PerkDescription.NggHMiscLineBreaker <- "\'Meat wall can not stop you, just break through it with brute force.\' \n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color] \n• Costs 4 AP and builds 30 Fatigue.\n• Allows you to break through enemy defensive line to reach those at the backline.";
::Const.Strings.PerkDescription.NggHMiscChampion <- "\'The toughest of the strongest of their kind.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Grants [color=" + ::Const.UI.Color.NegativeValue + "]Champion[/color] racial skill.";
::Const.Strings.PerkDescription.NggHMiscDaytime <- "\'There is nothing to be scared of the light. Embrace it!\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Greatly Reduces the penalty from [color=" + ::Const.UI.Color.NegativeValue + "]Daytime[/color] effect.\n• Increases the Resolve by [color=" + ::Const.UI.Color.PositiveValue + "]10[/color].";
::Const.Strings.PerkDescription.NggHMiscNighttime <- "Nighttime is your time.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n\n  Gains [color=" + ::Const.UI.Color.NegativeValue + "]Nocturnal[/color] effect which has these effects: \n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] Attack Damage.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] Melee Defense.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] Ranged Defense.\n• Unaffects by [color=" + ::Const.UI.Color.NegativeValue + "]Nighttime[/color] effect.";
::Const.Strings.PerkDescription.NggHMiscFairGame <- "\'A fair trade off.\' \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+25[/color] Melee Skill.\n• Gains [color=" + ::Const.UI.Color.PositiveValue + "]+25[/color] Ranged Skill.\n• Your attacks either deal [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] more damage or [color=" + ::Const.UI.Color.NegativeValue + "]50%[/color] less damage.";


